gpoppe/gitlabfall24

game.c

First version of game.c
Nathan C

nathan first commit

---

game.c

first version (Raquel Serratos)

Raquel's first version

---

game.c

Added comment to switch case 30
// ivan

ivan room 30

---

game.c

Alexis Jennar Gonzaga 1st Version

---

game.c

This is a first commit by Anushka.

First commit (Anushka)

---

game.c

Daniel First Version 

---

game.c

alexis first version

---

game.c

First Version (Cecilia Martinez)

Cecilia first commit

---

game.c

first version of game.c
Sidney M

sidneys first commit

---

game.c

AngelBautista

---

game.c

Picking my room for this assignment.

omarfirstversion

---

game.c

My first pull request
Esteban N

Esteban's first commit

---

game.c

First version of game.c.  
Corvalis Cohen
Notes:
I added my name to Room 9 to work on my final project

Corvalis First Commit

---

game.c

is it okay or do i have to change something

Nestor final code

---

amuhammadfinal.c

This program allows users to choose between five California State Universities and experience random events like receiving a scholarship or meeting the university president. It fulfills the project requirements by using:
- A loop
- An array
- A random number generator
- A separate function

Added amuhammadfinal program for final project

---

game.c

Adding 3 games, hopefully final product

Room 1 Game Final

---

game.c

incomplete version of code, testing merge-ability

Second commit, partially done

---

game.c

Cecilia  partial pull request 

---

game.c

Anushka Kalamkar (Room 6) Final Project code

Add mystery item game

---

game.c

Added the required functionality for the Final to room 23

Corvalis Final Functional Commit

---

game.c

Made sure to add void to prototype function

added room 26 code

---

game.c

Final Version

---

game.c

Reverts gpoppe/gitlabfall24#40

Revert "Final Version"

---

game.c

Cecilia Final pull request 

---

game.c

Angel's room 10 

---

game.c

Reverts gpoppe/gitlabfall24#50

Revert "Room 29 Alec Magsombol"

---

game.c

Not sure how far behind I'm on merges, but here's mine

Esteban Nino's Room 20 Code 1st Attempt

---

game.c

Implemented Room 19 with a quiz challenge

---

game.c

serina final

---

game.c

Added unique choices to room 26

---

game.c

This is my second request i have fixed the issue

room 10 second edition

---

game.c

Combined everything like Frankenstein after everyone submitted their code as instructed
Alexis Jennar Gonzaga - Room 7

Alexis Jennar Gonzaga 3rd Version
